# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/annotations/ratelimit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"eolymp/annotations/ratelimit.proto\x12\neolymp.api\x1a google/protobuf/descriptor.proto\"-\n\tRateLimit\x12\x0f\n\x05limit\x18\xae\xac\x01 \x01(\x02\x12\x0f\n\x05\x62urst\x18\xaf\xac\x01 \x01(\x05:J\n\tratelimit\x12\x1e.google.protobuf.MethodOptions\x18\xad\xac\x01 \x01(\x0b\x32\x15.eolymp.api.RateLimitB9Z7github.com/eolymp/go-sdk/eolymp/annotations;annotationsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.annotations.ratelimit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(ratelimit)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/eolymp/go-sdk/eolymp/annotations;annotations'
  _RATELIMIT._serialized_start=84
  _RATELIMIT._serialized_end=129
# @@protoc_insertion_point(module_scope)
