# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/ai/usage.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'eolymp/ai/usage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65olymp/ai/usage.proto\x12\teolymp.ai\"\x86\x01\n\x05Usage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x04\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x04\x12\x17\n\x0fthinking_tokens\x18\x03 \x01(\x04\x12\x14\n\x0ctotal_tokens\x18\x04 \x01(\x04\x12\x1c\n\x14\x63\x61\x63hed_prompt_tokens\x18\x05 \x01(\x04\x42\'Z%github.com/eolymp/go-sdk/eolymp/ai;aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.ai.usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/eolymp/go-sdk/eolymp/ai;ai'
  _globals['_USAGE']._serialized_start=37
  _globals['_USAGE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
