# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-python-esdk for more details.
"""Generated protocol buffer code."""

import urllib.parse
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()


class GroupServiceClient:
    def __init__(self, transport, url="https://api.eolymp.com"):
        self.transport = transport
        self.url = url

    def CreateGroup(self, request, **kwargs):
        path = "/groups"

        return self.transport.request(
            method="POST",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.community.CreateGroupOutput"),
            **kwargs,
        )

    def UpdateGroup(self, request, **kwargs):
        path = "/groups/"+urllib.parse.quote(request.group_id)

        # Cleanup URL parameters to avoid any ambiguity
        request.group_id = ""

        return self.transport.request(
            method="POST",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.community.UpdateGroupOutput"),
            **kwargs,
        )

    def DeleteGroup(self, request, **kwargs):
        path = "/groups/"+urllib.parse.quote(request.group_id)

        # Cleanup URL parameters to avoid any ambiguity
        request.group_id = ""

        return self.transport.request(
            method="DELETE",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.community.DeleteGroupOutput"),
            **kwargs,
        )

    def DescribeGroup(self, request, **kwargs):
        path = "/groups/"+urllib.parse.quote(request.group_id)

        # Cleanup URL parameters to avoid any ambiguity
        request.group_id = ""

        return self.transport.request(
            method="GET",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.community.DescribeGroupOutput"),
            **kwargs,
        )

    def ListGroups(self, request, **kwargs):
        path = "/groups"

        return self.transport.request(
            method="GET",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.community.ListGroupsOutput"),
            **kwargs,
        )

