# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/localization/project_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from eolymp.annotations import http_pb2 as eolymp_dot_annotations_dot_http__pb2
from eolymp.annotations import ratelimit_pb2 as eolymp_dot_annotations_dot_ratelimit__pb2
from eolymp.annotations import scope_pb2 as eolymp_dot_annotations_dot_scope__pb2
from eolymp.localization import project_pb2 as eolymp_dot_localization_dot_project__pb2
from eolymp.wellknown import expression_pb2 as eolymp_dot_wellknown_dot_expression__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)eolymp/localization/project_service.proto\x12\x13\x65olymp.localization\x1a\x1d\x65olymp/annotations/http.proto\x1a\"eolymp/annotations/ratelimit.proto\x1a\x1e\x65olymp/annotations/scope.proto\x1a!eolymp/localization/project.proto\x1a!eolymp/wellknown/expression.proto\"\xa7\x01\n\x11ListProjectsInput\x12\x0e\n\x06offset\x18\n \x01(\x05\x12\x0c\n\x04size\x18\x0b \x01(\x05\x12>\n\x07\x66ilters\x18( \x01(\x0b\x32-.eolymp.localization.ListProjectsInput.Filter\x1a\x34\n\x06\x46ilter\x12*\n\x02id\x18\x01 \x03(\x0b\x32\x1e.eolymp.wellknown.ExpressionID\"P\n\x12ListProjectsOutput\x12\r\n\x05total\x18\x01 \x01(\x05\x12+\n\x05items\x18\x02 \x03(\x0b\x32\x1c.eolymp.localization.Project\"*\n\x14\x44\x65scribeProjectInput\x12\x12\n\nproject_id\x18\x01 \x01(\t\"F\n\x15\x44\x65scribeProjectOutput\x12-\n\x07project\x18\x01 \x01(\x0b\x32\x1c.eolymp.localization.Project2\xe0\x02\n\x0eProjectService\x12\x9a\x01\n\x0cListProjects\x12&.eolymp.localization.ListProjectsInput\x1a\'.eolymp.localization.ListProjectsOutput\"9\x82\xe3\n\x15\x8a\xe3\n\x11l10n:project:read\xea\xe2\n\x0b\xf5\xe2\n\x00\x00\xa0@\xf8\xe2\n2\x82\xd3\xe4\x93\x02\x0b\x12\t/projects\x12\xb0\x01\n\x0f\x44\x65scribeProject\x12).eolymp.localization.DescribeProjectInput\x1a*.eolymp.localization.DescribeProjectOutput\"F\x82\xe3\n\x15\x8a\xe3\n\x11l10n:project:read\xea\xe2\n\x0b\xf5\xe2\n\x00\x00\xa0@\xf8\xe2\n2\x82\xd3\xe4\x93\x02\x18\x12\x16/projects/{project_id}B;Z9github.com/eolymp/go-sdk/eolymp/localization;localizationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.localization.project_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z9github.com/eolymp/go-sdk/eolymp/localization;localization'
  _PROJECTSERVICE.methods_by_name['ListProjects']._options = None
  _PROJECTSERVICE.methods_by_name['ListProjects']._serialized_options = b'\202\343\n\025\212\343\n\021l10n:project:read\352\342\n\013\365\342\n\000\000\240@\370\342\n2\202\323\344\223\002\013\022\t/projects'
  _PROJECTSERVICE.methods_by_name['DescribeProject']._options = None
  _PROJECTSERVICE.methods_by_name['DescribeProject']._serialized_options = b'\202\343\n\025\212\343\n\021l10n:project:read\352\342\n\013\365\342\n\000\000\240@\370\342\n2\202\323\344\223\002\030\022\026/projects/{project_id}'
  _LISTPROJECTSINPUT._serialized_start=236
  _LISTPROJECTSINPUT._serialized_end=403
  _LISTPROJECTSINPUT_FILTER._serialized_start=351
  _LISTPROJECTSINPUT_FILTER._serialized_end=403
  _LISTPROJECTSOUTPUT._serialized_start=405
  _LISTPROJECTSOUTPUT._serialized_end=485
  _DESCRIBEPROJECTINPUT._serialized_start=487
  _DESCRIBEPROJECTINPUT._serialized_end=529
  _DESCRIBEPROJECTOUTPUT._serialized_start=531
  _DESCRIBEPROJECTOUTPUT._serialized_end=601
  _PROJECTSERVICE._serialized_start=604
  _PROJECTSERVICE._serialized_end=956
# @@protoc_insertion_point(module_scope)
