# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/universe/space_user_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'eolymp/universe/space_user_config.proto\x12\x0f\x65olymp.universe\"\xd0\x05\n\nUserConfig\x12@\n\x08\x62\x61secamp\x18\x64 \x01(\x0b\x32,.eolymp.universe.UserConfig.BasecampProviderH\x00\x12:\n\x05local\x18\x65 \x01(\x0b\x32).eolymp.universe.UserConfig.LocalProviderH\x00\x12\x38\n\x04oidc\x18\x66 \x01(\x0b\x32(.eolymp.universe.UserConfig.OIDCProviderH\x00\x12>\n\x0c\x64isplay_name\x18\xc8\x01 \x01(\x0e\x32\'.eolymp.universe.UserConfig.DisplayName\x12\x1f\n\x16\x64isplay_name_attribute\x18\xc9\x01 \x01(\t\x1a\x12\n\x10\x42\x61secampProvider\x1a\x86\x01\n\rLocalProvider\x12\x1d\n\x15\x61llow_modify_password\x18\x65 \x01(\x08\x12\x1b\n\x13\x61llow_modify_basics\x18\x66 \x01(\x08\x12\x1a\n\x12\x61llow_modify_email\x18g \x01(\x08\x12\x1d\n\x15\x61llow_modify_nickname\x18h \x01(\x08\x1a\xcc\x01\n\x0cOIDCProvider\x12\x12\n\tclient_id\x18\xd2\x01 \x01(\t\x12\x16\n\rclient_secret\x18\xd3\x01 \x01(\t\x12\x0f\n\x06issuer\x18\xdc\x01 \x01(\t\x12\x1b\n\x12\x61uthorize_endpoint\x18\xdd\x01 \x01(\t\x12\x17\n\x0etoken_endpoint\x18\xde\x01 \x01(\t\x12\x16\n\rkeys_endpoint\x18\xdf\x01 \x01(\t\x12\x1a\n\x11userinfo_endpoint\x18\xe0\x01 \x01(\t\x12\x15\n\x0credirect_uri\x18\xe1\x01 \x01(\t\"1\n\x0b\x44isplayName\x12\t\n\x05LOGIN\x10\x00\x12\x08\n\x04NAME\x10\x01\x12\r\n\tATTRIBUTE\x10\x02\x42\n\n\x08providerB3Z1github.com/eolymp/go-sdk/eolymp/universe;universeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.universe.space_user_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/eolymp/go-sdk/eolymp/universe;universe'
  _USERCONFIG._serialized_start=61
  _USERCONFIG._serialized_end=781
  _USERCONFIG_BASECAMPPROVIDER._serialized_start=356
  _USERCONFIG_BASECAMPPROVIDER._serialized_end=374
  _USERCONFIG_LOCALPROVIDER._serialized_start=377
  _USERCONFIG_LOCALPROVIDER._serialized_end=511
  _USERCONFIG_OIDCPROVIDER._serialized_start=514
  _USERCONFIG_OIDCPROVIDER._serialized_end=718
  _USERCONFIG_DISPLAYNAME._serialized_start=720
  _USERCONFIG_DISPLAYNAME._serialized_end=769
# @@protoc_insertion_point(module_scope)
