# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/basecamp/freelancer_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'eolymp/basecamp/freelancer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from eolymp.annotations import http_pb2 as eolymp_dot_annotations_dot_http__pb2
from eolymp.annotations import ratelimit_pb2 as eolymp_dot_annotations_dot_ratelimit__pb2
from eolymp.annotations import scope_pb2 as eolymp_dot_annotations_dot_scope__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(eolymp/basecamp/freelancer_service.proto\x12\x0f\x65olymp.basecamp\x1a\x1d\x65olymp/annotations/http.proto\x1a\"eolymp/annotations/ratelimit.proto\x1a\x1e\x65olymp/annotations/scope.proto\"\x1f\n\x1d\x44\x65scribeFreelancerStatusInput\"\xaf\x01\n\x1e\x44\x65scribeFreelancerStatusOutput\x12\x46\n\x06status\x18\x01 \x01(\x0e\x32\x36.eolymp.basecamp.DescribeFreelancerStatusOutput.Status\"E\n\x06Status\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\x0c\n\x08UNSIGNED\x10\x01\x12\x0b\n\x07PENDING\x10\x02\x12\x0c\n\x08\x43OMPLETE\x10\x03\"U\n\x1bUpdateFreelancerStatusInput\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"0\n\x1cUpdateFreelancerStatusOutput\x12\x10\n\x08sign_url\x18\x01 \x01(\t2\xf1\x02\n\x11\x46reelancerService\x12\xaf\x01\n\x18\x44\x65scribeFreelancerStatus\x12..eolymp.basecamp.DescribeFreelancerStatusInput\x1a/.eolymp.basecamp.DescribeFreelancerStatusOutput\"2\xea\xe2\n\x0b\xf5\xe2\n\x00\x00\x80?\xf8\xe2\n\n\x82\xd3\xe4\x93\x02\x1d\x12\x1b/basecamp/freelancer-status\x12\xa9\x01\n\x16UpdateFreelancerStatus\x12,.eolymp.basecamp.UpdateFreelancerStatusInput\x1a-.eolymp.basecamp.UpdateFreelancerStatusOutput\"2\xea\xe2\n\x0b\xf5\xe2\n\x00\x00\x80?\xf8\xe2\n\n\x82\xd3\xe4\x93\x02\x1d\"\x1b/basecamp/freelancer-statusB3Z1github.com/eolymp/go-sdk/eolymp/basecamp;basecampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.basecamp.freelancer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/eolymp/go-sdk/eolymp/basecamp;basecamp'
  _globals['_FREELANCERSERVICE'].methods_by_name['DescribeFreelancerStatus']._loaded_options = None
  _globals['_FREELANCERSERVICE'].methods_by_name['DescribeFreelancerStatus']._serialized_options = b'\352\342\n\013\365\342\n\000\000\200?\370\342\n\n\202\323\344\223\002\035\022\033/basecamp/freelancer-status'
  _globals['_FREELANCERSERVICE'].methods_by_name['UpdateFreelancerStatus']._loaded_options = None
  _globals['_FREELANCERSERVICE'].methods_by_name['UpdateFreelancerStatus']._serialized_options = b'\352\342\n\013\365\342\n\000\000\200?\370\342\n\n\202\323\344\223\002\035\"\033/basecamp/freelancer-status'
  _globals['_DESCRIBEFREELANCERSTATUSINPUT']._serialized_start=160
  _globals['_DESCRIBEFREELANCERSTATUSINPUT']._serialized_end=191
  _globals['_DESCRIBEFREELANCERSTATUSOUTPUT']._serialized_start=194
  _globals['_DESCRIBEFREELANCERSTATUSOUTPUT']._serialized_end=369
  _globals['_DESCRIBEFREELANCERSTATUSOUTPUT_STATUS']._serialized_start=300
  _globals['_DESCRIBEFREELANCERSTATUSOUTPUT_STATUS']._serialized_end=369
  _globals['_UPDATEFREELANCERSTATUSINPUT']._serialized_start=371
  _globals['_UPDATEFREELANCERSTATUSINPUT']._serialized_end=456
  _globals['_UPDATEFREELANCERSTATUSOUTPUT']._serialized_start=458
  _globals['_UPDATEFREELANCERSTATUSOUTPUT']._serialized_end=506
  _globals['_FREELANCERSERVICE']._serialized_start=509
  _globals['_FREELANCERSERVICE']._serialized_end=878
# @@protoc_insertion_point(module_scope)
