# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-python-esdk for more details.
"""Generated protocol buffer code."""

import urllib.parse
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()


class RuleServiceClient:
    def __init__(self, transport, url="https://api.eolymp.com"):
        self.transport = transport
        self.url = url

    def ListRules(self, request, **kwargs):
        path = "/automation/rules"

        return self.transport.request(
            method="GET",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.automation.ListRulesOutput"),
            **kwargs,
        )

    def CreateRule(self, request, **kwargs):
        path = "/automation/rules"

        return self.transport.request(
            method="POST",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.automation.CreateRuleOutput"),
            **kwargs,
        )

    def DescribeRule(self, request, **kwargs):
        path = "/automation/rules/"+urllib.parse.quote(request.rule_id)

        # Cleanup URL parameters to avoid any ambiguity
        request.rule_id = ""

        return self.transport.request(
            method="GET",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.automation.DescribeRuleOutput"),
            **kwargs,
        )

    def UpdateRule(self, request, **kwargs):
        path = "/automation/rules/"+urllib.parse.quote(request.rule_id)

        # Cleanup URL parameters to avoid any ambiguity
        request.rule_id = ""

        return self.transport.request(
            method="PUT",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.automation.UpdateRuleOutput"),
            **kwargs,
        )

    def DeleteRule(self, request, **kwargs):
        path = "/automation/rules/"+urllib.parse.quote(request.rule_id)

        # Cleanup URL parameters to avoid any ambiguity
        request.rule_id = ""

        return self.transport.request(
            method="DELETE",
            url=self.url+path,
            request_data=request,
            response_symbol=_sym_db.GetSymbol("eolymp.automation.DeleteRuleOutput"),
            **kwargs,
        )

