# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/l10n/glossary_entry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'eolymp/l10n/glossary_entry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n eolymp/l10n/glossary_entry.proto\x12\x0b\x65olymp.l10n\"\xbd\x01\n\rGlossaryEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x13\n\x0btranslation\x18\x03 \x01(\t\x12\x0e\n\x06locale\x18\x04 \x01(\t\x1am\n\x05Patch\x12\x11\n\x04term\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0btranslation\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06locale\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x07\n\x05_termB\x0e\n\x0c_translationB\t\n\x07_localeB+Z)github.com/eolymp/go-sdk/eolymp/l10n;l10nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.l10n.glossary_entry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/eolymp/go-sdk/eolymp/l10n;l10n'
  _globals['_GLOSSARYENTRY']._serialized_start=50
  _globals['_GLOSSARYENTRY']._serialized_end=239
  _globals['_GLOSSARYENTRY_PATCH']._serialized_start=130
  _globals['_GLOSSARYENTRY_PATCH']._serialized_end=239
# @@protoc_insertion_point(module_scope)
