# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/atlas/script.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'eolymp/atlas/script.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from eolymp.executor import file_pb2 as eolymp_dot_executor_dot_file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65olymp/atlas/script.proto\x12\x0c\x65olymp.atlas\x1a\x1a\x65olymp/executor/file.proto\"\x82\x03\n\x06Script\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06secret\x18\x07 \x01(\x08\x12\x0f\n\x07runtime\x18\n \x01(\t\x12\x0e\n\x06source\x18\x0b \x01(\t\x12$\n\x05\x66iles\x18\x14 \x03(\x0b\x32\x15.eolymp.executor.File\x1a/\n\x05\x45xtra\"&\n\x05\x46ield\x12\x11\n\rUNKNOWN_EXTRA\x10\x00\x12\n\n\x06SOURCE\x10\x01\x1a\xd5\x01\n\x05Patch\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06secret\x18\x07 \x01(\x08H\x01\x88\x01\x01\x12\x14\n\x07runtime\x18\n \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06source\x18\x0b \x01(\tH\x03\x88\x01\x01\x12$\n\x05\x66iles\x18\x14 \x03(\x0b\x32\x15.eolymp.executor.File\x12\x18\n\x0bunset_files\x18\x15 \x01(\x08H\x04\x88\x01\x01\x42\x07\n\x05_nameB\t\n\x07_secretB\n\n\x08_runtimeB\t\n\x07_sourceB\x0e\n\x0c_unset_filesB-Z+github.com/eolymp/go-sdk/eolymp/atlas;atlasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eolymp.atlas.script_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/eolymp/go-sdk/eolymp/atlas;atlas'
  _globals['_SCRIPT']._serialized_start=72
  _globals['_SCRIPT']._serialized_end=458
  _globals['_SCRIPT_EXTRA']._serialized_start=195
  _globals['_SCRIPT_EXTRA']._serialized_end=242
  _globals['_SCRIPT_EXTRA_FIELD']._serialized_start=204
  _globals['_SCRIPT_EXTRA_FIELD']._serialized_end=242
  _globals['_SCRIPT_PATCH']._serialized_start=245
  _globals['_SCRIPT_PATCH']._serialized_end=458
# @@protoc_insertion_point(module_scope)
