name: Upload to PyPi
on: [ push ]

jobs:
  upload-pypi:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    container:
      image: alpine:3.17
    steps:
      - name: Install
        run: |
          apk -U add git python3 python3-dev py3-pip libffi-dev libressl-dev
          pip3 install setuptools wheel cryptography twine
          git config --global --add safe.directory $(pwd)

      - name: Clone
        uses: actions/checkout@v2

      - name: Upload
        env:
          TWINE_USERNAME:  "__token__"
          TWINE_PASSWORD:  "${{ secrets.pypi_token }}"
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          
          python3 setup.py sdist bdist_wheel && \
          python3 -m twine upload dist/*
